### PR TITLE
Enable GPU persistent mode in unit override file

### LINKED ISSUE #54: Hot GPU on Tatooine
On Tatooine (Ubuntu 20.04)
```
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3070    Off  | 00000000:19:00.0 Off |                  N/A |
| 30%   49C    P0    48W / 220W |      0MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3070    Off  | 00000000:1A:00.0 Off |                  N/A |
| 30%   53C    P0    51W / 220W |      0MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 3070    Off  | 00000000:67:00.0 Off |                  N/A |
| 30%   54C    P0    48W / 220W |      0MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 3070    Off  | 00000000:68:00.0 Off |                  N/A |
| 30%   54C    P0    22W / 220W |      0MiB /  7974MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

It's too hot for the idle state.

### PR DESCRIPTION
**Pull request by gqqnbig**
closes #54

### CODE REVIEW

**Comment by gqqnbig** [comment]
I know the commit works for Tatooine. Can you check if it reduces the temperature on Eureka?

**Comment by wulamao** [comment]
image
I'm not quite sure exactly what the “before” and “after” comparisons are. So far, there does seem to be a big difference between GPU temperatures in use and GPU temperatures not in use. The unused GPU temperature is 33C, as shown in the graph.

**Comment by gqqnbig** [comment]
Every time the configuration changes, slurm must be restarted. For this case, you need to use
`sudo systemctl status slurmd` for checking slurmd state, `sudo systemctl restart slurmd` to restart slurmd.


Use `sudo scontrol update nodename=eureka state=drain` to drain Eureka so that no new jobs can start if you never find a chance  when no running jobs on Eureka.

**Comment by wulamao** [comment]
Before:
will@eureka:~$ nvidia-smi
Mon Nov 22 15:35:12 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 27%   28C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 27%   28C    P8     7W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:1C:00.0 Off |                  N/A |
| 27%   28C    P8     8W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:1D:00.0 Off |                  N/A |
| 27%   28C    P8    19W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:1E:00.0 Off |                  N/A |
| 27%   29C    P8    20W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:3D:00.0 Off |                  N/A |
| 27%   28C    P8     4W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:3E:00.0 Off |                  N/A |
| 27%   27C    P8    21W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:3F:00.0 Off |                  N/A |
| 27%   28C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   8  GeForce RTX 208...  Off  | 00000000:40:00.0 Off |                  N/A |
| 27%   29C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   9  GeForce RTX 208...  Off  | 00000000:41:00.0 Off |                  N/A |
| 27%   28C    P8    18W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by wulamao** [comment]
After:
```bash
will@eureka:/home/qiqig/mpi-servers$ nvidia-smi
Mon Nov 22 16:15:14 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 27%   30C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 27%   29C    P8     8W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:1C:00.0 Off |                  N/A |
| 27%   30C    P8     8W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:1D:00.0 Off |                  N/A |
| 27%   29C    P8    18W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:1E:00.0 Off |                  N/A |
| 27%   30C    P8    20W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:3D:00.0 Off |                  N/A |
| 27%   29C    P8     3W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:3E:00.0 Off |                  N/A |
| 27%   29C    P8    20W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:3F:00.0 Off |                  N/A |
| 49%   55C    P2    78W / 260W |   3294MiB / 11019MiB |     21%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   8  GeForce RTX 208...  Off  | 00000000:40:00.0 Off |                  N/A |
| 27%   30C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   9  GeForce RTX 208...  Off  | 00000000:41:00.0 Off |                  N/A |
| 27%   30C    P8    17W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    7   N/A  N/A   1118171      C   python                           3291MiB |
+-----------------------------------------------------------------------------+

**Comment by wulamao** [comment]
The GPU temperature is close to room temperature, when all the GPUs are idle,. However, when a GPU is working, the overall temperature is slightly higher. I think this is normal, the GPU's temperature rises and so does the internal temperature of the cabinet.

**Comment by wulamao** [comment]
```bash
will@eureka:~$ sudo systemctl cat slurmd
# /home/qiqig/mpi-servers/slurm/etc/systemd/system/multi-user.target.wants/slurmd.service
[Unit]
Description=Slurm node daemon
After=munge.service network.target remote-fs.target
ConditionPathExists=/etc/slurm-llnl/slurm.conf
Documentation=man:slurmd(8)

[Service]
Type=forking
EnvironmentFile=-/etc/default/slurmd
ExecStartPre=/etc/slurm-llnl/randomize-gpu
ExecStart=/usr/sbin/slurmd $SLURMD_OPTIONS
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/run/slurmd.pid
KillMode=process
LimitNOFILE=131072
LimitMEMLOCK=infinity
LimitSTACK=infinity
Delegate=yes
TasksMax=infinity

[Install]
WantedBy=multi-user.target

# /home/qiqig/mpi-servers/slurm/etc/systemd/system/slurmd.service.d/persistent-driver.conf
ExecStartPre=/usr/bin/nvidia-smi -pm 1
```
I checked the configeration use `sudo systemctl cat slurmd`, the commond to start `persistence` mode exist, but does not work.

**Comment by gqqnbig** [comment]
> I checked the configuration use sudo systemctl cat slurmd, the commond to start persistence mode exist, but does not work.

Good catch! 

I think I've fixed this issue. Can you verify? Pay attention to how cd12a45 fails the tests and bb8f56e passes the tests.

**Comment by wulamao** [comment]
```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:1A:00.0 Off |                  N/A |
| 27%   24C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:1B:00.0 Off |                  N/A |
| 27%   24C    P8     6W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  On   | 00000000:1C:00.0 Off |                  N/A |
| 27%   24C    P8     8W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  On   | 00000000:1D:00.0 Off |                  N/A |
| 27%   24C    P8    19W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  On   | 00000000:1E:00.0 Off |                  N/A |
| 27%   25C    P8    19W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  On   | 00000000:3D:00.0 Off |                  N/A |
| 27%   23C    P8     2W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  On   | 00000000:3E:00.0 Off |                  N/A |
| 27%   24C    P8    20W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  On   | 00000000:3F:00.0 Off |                  N/A |
| 27%   24C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   8  GeForce RTX 208...  On   | 00000000:40:00.0 Off |                  N/A |
| 27%   25C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   9  GeForce RTX 208...  On   | 00000000:41:00.0 Off |                  N/A |
| 27%   24C    P8    17W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
I checked power state on Eureka with `nvidia-smi`. As the results shown, 'Persistence-M' state is on now and total energy cost is lower than  before. BTY, The overall drop in temperature may be attributed to the colder weather.

**Comment by gqqnbig** [comment]
Any machine may benefit from the persistent mode, not necessarily mpi-servers.

**Pull request merged**
