### PR TITLE
Trim real memory

### PR DESCRIPTION
**Pull request by gqqnbig**
The total memory of Tatooine was 128517. 

Then I rebooted Tatooine many times, and updated BIOS. 

Then the total memory became 128516.

I'm not sure if the BIOS update or something else would change total memory.

To avoid memory size change, trim memory size to 000.

### CODE REVIEW

**Comment by Lu-MPI** [comment]
LGTM

根据文档的描述，适当减小RealMemory不会影响任务运行。

https://slurm.schedmd.com/slurm.conf.html#OPT_RealMemory

**Comment by wulamao** [comment]
I try the command `slurmd -C` on Tatooine and get :
```bash
(base) william@tatooine:~/shared$ slurmd -C
NodeName=tatooine CPUs=20 Boards=1 SocketsPerBoard=1 CoresPerSocket=10 ThreadsPerCore=2 RealMemory=128515
UpTime=7-01:48:29
```
However, it is not same as `RealMemory=128000` in  `slurm.conf`.
So, we need to further verify that this setting `RealMemory` works under the current `slurm` configuration.

**Comment by gqqnbig** [comment]
还有，你相信总内存大小会变化吗？难道内存条上突然丢了1MB？

**Comment by Lu-MPI** [comment]
根据文档：
  

> RealMemory 
Size of real memory on the node in megabytes (e.g. "2048"). The default value is 1. Lowering RealMemory with the goal of setting aside some amount for the OS and not available for job allocations will not work as intended if Memory is not set as a consumable resource in SelectTypeParameters. So one of the *_Memory options need to be enabled for that goal to be accomplished. Also see MemSpecLimit.

我们还需要设置至少一个 *_Memory 选项让RealMemory 生效。

**Comment by wulamao** [comment]
不知道你们使用何种方法获取  Total Memory。
我使用了`/proc/meminfo`。
然而，这种方法获得的 Tatooine Total Memory 数值是128515 m。
根据  [DMESG](https://www.programmerall.com/article/8685181493/) 信息的说明，Total Memory数值表示的是系统初始化之后，剩余的可供 kernal 使用的大小。因此，它受到初始化过程中，BIOS，kernal本身的占用影响。

**Comment by gqqnbig** [comment]
> 不知道你们使用何种方法获取 Total Memory。 我使用了`/proc/meminfo`。 然而，这种方法获得的 Tatooine Total Memory 数值是128515 m。 根据 [DMESG](https://www.programmerall.com/article/8685181493/) 信息的说明，Total Memory数值表示的是系统初始化之后，剩余的可供 kernal 使用的大小。因此，它受到初始化过程中，BIOS，kernal本身的占用影响。

That's a good finding. It reinforces my belief that RealMemory is variable and we should be prevented from editing the file consistently.

So, have you tested the file with no RealMemory? Did you make sure in practice the master node and the slave nodes work with no RealMemory?

If yes, can you push a commit to this PR that removes RealMemory?

**Comment by wulamao** [comment]
> Lu知道怎么发起一个全新的PR，但这里我要你修改这个现有的PR。你如果不会的话我教你。
 Ok，让我来尝试一下 ： ）

**Comment by wulamao** [comment]
> > 不知道你们使用何种方法获取 Total Memory。 我使用了`/proc/meminfo`。 然而，这种方法获得的 Tatooine Total Memory 数值是128515 m。 根据 [DMESG](https://www.programmerall.com/article/8685181493/) 信息的说明，Total Memory数值表示的是系统初始化之后，剩余的可供 kernal 使用的大小。因此，它受到初始化过程中，BIOS，kernal本身的占用影响。
> 
> That's a good finding. It reinforces my belief that RealMemory is variable and we should be prevented from editing the file consistently.
> 
> So, have you tested the file with no RealMemory? Did you make sure in practice the master node and the slave nodes work if we do not set RealMemory?
> 
> If yes, can you push a commit to this PR that removes RealMemory? Once done, assign back to me and let me review it.

Yes, Tatooine has worked without setting RealMemory.

**Comment by gqqnbig** [comment]
1. 把RealMemory刪掉，不要comment 。如果comment out是爲了容易取回的話，git保存了所有文件的所有歷史，我們可以從git裏取回。
2. 把eureka的RealMemory也刪掉。
3. 把行尾空格刪掉。
gvim_2022-01-15_20-50-13

**Comment by wulamao** [comment]
> 1. 把RealMemory刪掉，不要comment 。如果comment out是爲了容易取回的話，git保存了所有文件的所有歷史，我們可以從git裏取回。
> 2. 把eureka的RealMemory也刪掉。
> 3. 把行尾空格刪掉。
>    gvim_2022-01-15_20-50-13

Done.

**Comment by gqqnbig** [comment]
If an sbatch file specifies 

```
#SBATCH --mem=10G
```

sbatch will throw error.

```console
$ sbatch tatooine.slurm
sbatch: error: Memory specification can not be satisfied
sbatch: error: Batch job submission failed: Requested node configuration is not available
```

**Pull request merged**
